name: Build docker image

permissions:
    contents: read

on:
    push:
        branches:
          - "*"
        tags-ignore:
          - "*"

jobs:
    build-image:
        name: Build the image
        runs-on: ${{ matrix.run-on }}
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                include:
                  - { platform: "linux/386", run-on: "ubuntu-22.04", qemu-platform: "386" }
                  - { platform: "linux/amd64", run-on: "ubuntu-22.04", qemu-platform: "" }
                  - { platform: "linux/ppc64le", run-on: "ubuntu-22.04", qemu-platform: "ppc64le" }
                  - { platform: "linux/s390x", run-on: "ubuntu-22.04", qemu-platform: "s390x" }
                  - { platform: "linux/riscv64", run-on: "ubuntu-22.04", qemu-platform: "riscv64" }
                  - { platform: "linux/arm/v6", run-on: "ubuntu-22.04-arm", qemu-platform: "arm" }
                  - { platform: "linux/arm/v7", run-on: "ubuntu-22.04-arm", qemu-platform: "arm" }
                  - { platform: "linux/arm64/v8", run-on: "ubuntu-22.04-arm", qemu-platform: "" }

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              if: ${{ matrix.qemu-platform != '' }}
              with:
                # mips64le
                # loong64
                # s390x
                # ppc64le
                # riscv64
                # 386
                # mips64
                # amd64
                platforms: ${{ matrix.qemu-platform }}
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build docker image
              run: make build-alpine
              env:
                DOCKER_BUILDKIT: 1
                PLATFORM: ${{ matrix.platform }}

            - name: Test docker image
              run: make test-alpine
              env:
                PLATFORM: ${{ matrix.platform }}
                DOCKER_DEFAULT_PLATFORM: ${{ matrix.platform }}
