name: Build and test the docker image

permissions:
  contents: read

on: [push]

jobs:
    build-docker-image:
        name: Build and test image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Build docker image
              run: make build-alpine
            - name: Test docker image
              run: make test-alpine
