name: Build docker image

permissions:
    contents: read

on:
    push:
        branches:
          - "*"
        tags-ignore:
          - "*"

jobs:
    build-image:
        name: Build the image
        runs-on: ${{ matrix.run-on }}
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                platform: ["linux/386"]
                run-on: ["ubuntu-22.04"]
                includes:
                  - { platform: "linux/amd64", run-on: "ubuntu-22.04" }
                  - { platform: "linux/ppc64le", run-on: "ubuntu-22.04" }
                  - { platform: "linux/s390x", run-on: "ubuntu-22.04" }
                  - { platform: "linux/riscv64", run-on: "ubuntu-22.04" }
                  - { platform: "linux/arm/v6", run-on: "ubuntu-22.04-arm" }
                  - { platform: "linux/arm/v7", run-on: "ubuntu-22.04-arm" }
                  - { platform: "linux/arm64/v8", run-on: "ubuntu-22.04-arm" }

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build docker image
              run: make build-alpine
              env:
                DOCKER_BUILDKIT: 1
                PLATFORM: ${{ matrix.platform }}

            - name: Test docker image
              run: make test-alpine
              env:
                DOCKER_DEFAULT_PLATFORM: ${{ matrix.platform }}
