name: Build docker image

permissions:
    contents: read

on:
    push:
        branches:
          - "*"
        tags-ignore:
          - "*"

jobs:
    build-image:
        name: Build the image
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                # Disabled: "linux/ppc64le", "linux/s390x"
                # See: https://github.com/hickory-dns/hickory-dns/issues/2065
                platform: ["linux/386", "linux/amd64", "linux/arm/v6", "linux/arm/v7", "linux/arm64/v8"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build docker image
              run: make build-alpine
              env:
                DOCKER_BUILDKIT: 1
                PLATFORM: ${{ matrix.platform }}

            - name: Test docker image
              if: ${{ matrix.platform == 'linux/amd64' }}
              run: make test-alpine
